version: '3.8'

services:
  wordpress:
    build: .
    ports:
      - "8080:80"  
    volumes:
      - ./wp-content:/var/www/html/wp-content  
    environment:
      DB_HOST: localhost
      DB_NAME: face
      DB_USER: root
      DB_PASSWORD: "" 
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: face
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  
    ports:
      - "3310:3306"  

volumes:
  db_data:
