# Usa una imagen base de Node.js
FROM node:20.14.0

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos de dependencias
COPY backend/package*.json ./

# Instala todas las dependencias, incluidas las devDependencies
RUN npm install

# Copia el resto del código de la aplicación al contenedor
COPY backend .

# Exponer el puerto que usa el backend
EXPOSE 3000

# Comando para iniciar el backend
CMD ["npm", "start"]
