# Dockerfile.frontend
FROM node:20.14.0

# Crear y configurar el directorio de trabajo
WORKDIR /app

# Copiar dependencias del frontend
COPY frontend/package*.json ./
RUN npm ci

# Copiar el código fuente del frontend
COPY frontend .

# Exponer el puerto usado por el frontend
EXPOSE 5173

# Comando para iniciar el frontend
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
